### ISSUE TITLE
EXTERNALBROWSER based authentication not working, getting "Cannot read properties of null (reading 'proofKey')" error.

### ISSUE THREAD

**Issue by rajeshmuraleedharan** [Snowflake-Labs/sqltools-snowflake-driver#70]
EXTERNALBROWSER based authentication not working, getting "Cannot read properties of null (reading 'proofKey')" error.

Here is the error log details
[1691774054735] INFO  (ext): EXECUTING COMMAND => sqltools.selectConnection
[1691774054736] INFO  (ext): EXECUTING COMMAND => sqltools.getConnections
[1691774054736] INFO  (ls): REQUEST RECEIVED => connection/GetConnectionsRequest
[1691774054737] INFO  (ext): EXECUTING COMMAND => sqltools.getConnections
[1691774054738] INFO  (ls): REQUEST RECEIVED => connection/GetConnectionsRequest
[1691774054738] INFO  (ls): REQUEST RECEIVED => connection/ConnectRequest
[1691774054738] INFO  (ls): Connection instance created for holtcat.east-us-2.azure.
    ns: "conn-manager"
[1691774055015] ERROR (ls): TypeError: Cannot read properties of null (reading 'proofKey')
    at /Users/uesrname/.vscode/extensions/koszti.snowflake-driver-for-sqltools-0.5.0/node_modules/snowflake-sdk/lib/authentication/auth_web.js:174:24
    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async auth_web.authenticate (/Users/rajeshmuraleedharan/.vscode/extensions/koszti.snowflake-driver-for-sqltools-0.5.0/node_modules/snowflake-sdk/lib/authentication/auth_web.js:75:18)
    at async Connection.connectAsync (/Users/rajeshmuraleedharan/.vscode/extensions/koszti.snowflake-driver-for-sqltools-0.5.0/node_modules/snowflake-sdk/lib/connection/connection.js:262:7)

**Comment by archiewood** [comment]
Also getting this
